

export const metadata = {
  title: "Bill 365 || Feature",
  description: "Generated by create next app",
};

export default function FeatureLayout({ children }) {
  return <section>{children}</section>
}