

export const metadata = {
  title: "Bill 365 || About Us",
  description: "Generated by create next app",
};

export default function AboutLayout({ children }) {
  return <section>{children}</section>
}