

export const metadata = {
  title: "Bill 365 || Contact Us",
  description: "Generated by create next app",
};

export default function ContactLayout({ children }) {
  return <section>{children}</section>
}