

export const metadata = {
  title: "Bill 365 || Terms Conditions",
  description: "Generated by create next app",
};

export default function Terms_ConditionsLayout({ children }) {
  return <section>{children}</section>
}