import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import "../style/custom.css";
import 'font-awesome/css/font-awesome.min.css';

// app/layout.js or your top-level file
import { Jost } from 'next/font/google';
import Navbar from "@/component/Navbar";
import FooterCus from "@/component/FooterCus";

const jost = Jost({
  subsets: ['latin'],
  weight: ['100', '400', '700', '900'], // You can choose weights you need
  variable: '--font-jost',
});


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "GST Billing Software in India for PC Mobile &#8211; Best Billing Software for Small Business",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${jost.variable}`}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {children}
        <FooterCus />
      </body>
    </html>
  );
}
