

export const metadata = {
  title: "Bill 365 || Privacy Policy",
  description: "Generated by create next app",
};

export default function Privacy_PolicyLayout({ children }) {
  return <section>{children}</section>
}