

export const metadata = {
  title: "Bill 365 || Blog List",
  description: "Generated by create next app",
};

export default function BlogLayout({ children }) {
  return <section>{children}</section>
}